export const queryKeys = {
  accounts: ['accounts'] as const,
  transactions: ['transactions'] as const,
  accountSnapshots: ['accountSnapshots'] as const,
  stocks: ['stocks'] as const,
  stockLocations: ['stockLocations'] as const,
  stockSales: ['stockSales'] as const,
  stockSalesSummary: ['stockSales', 'summary'] as const,
  cryptos: ['cryptos'] as const,
  cryptoLocations: ['cryptoLocations'] as const,
  cryptoSales: ['cryptoSales'] as const,
  cryptoSalesSummary: ['cryptoSales', 'summary'] as const,
  golds: ['golds'] as const,
  goldLocations: ['goldLocations'] as const,
  goldSales: ['goldSales'] as const,
  goldSalesSummary: ['goldSales', 'summary'] as const,
  assetPrices: ['assetPrices'] as const,
  portfolioSnapshots: ['portfolioSnapshots'] as const,
} as const
